// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocdhqaeyceaufqrlaeti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZGhxYWV5Y2VhdWZxcmxhZXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODcxMjQsImV4cCI6MjA4NTM2MzEyNH0.5Ssa5VXJkh2TFjFXuk5x_hBCV-kwRjBVjluvdWg8jLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});